#################
# TimedRankups  #
#################

handle rankup commands:
  - "lp user %player% parent add %rank_name%"
  - "lp user %player% parent remove %old_rank_name%"

default rank: "default"

MySQL:
  Host: "localhost"
  Port: "3306"
  Username: "usrcx_locsql58"
  Password: "BhN7AsMqAeAUQkKaQ76GVkK43EJbxXuVsLcVEGQGN2pkeWq2eaQKwGqJb5cFBWdaaNs2GxZUe6v"
  Database: "survival"

enabled rankups: # Reverse order in order to have the priority to high ranks.
  - "red"
  - "green"
  - "aqua"
  - "purple"
  - "yellow"
  - "white"
  - "gold"
  - "cyan"
  - "pink"
  - "default"

no more ranks: "&cUltimo Rango"

rankups:
  default:
    time: 0 # seconds, put 0 for default.
    prefix: "&7Usuario"
  pink:
    time: 604800 # 1 week
    prefix: "&5Pink"
  cyan:
    time: 2629800 # 1 month
    prefix: "&3Cyan"
  gold:
    time: 7889400 # 3 months
    prefix: "&6Gold"
  white:
    time: 21038400 # 8 months
    prefix: "&fWhite"
  yellow:
    time: 26298000 # 10 months
    prefix: "&eYellow"
  purple:
    time: 31557600 # 1 year
    prefix: "&dPurple"
  aqua:
    time: 39447000 # 1 year and 3 months
    prefix: "&bAqua"
  green:
    time: 47336400 # 1 year and 6 months
    prefix: "&aGreen"
  red:
    time: 63115200 # 2 years
    prefix: "&4Red"

commands:
  see:
    next:
      - "&7&m&l----------------------------"
      - "&7Te falta &b%parsedTime% &7para"
      - "&7obtener el rango %new_rank_prefix%"
      - "&7&m&l----------------------------"
    noMore:
      - "&7&m&l----------------------------"
      - "&7You're in the last rankup."
      - "&7&m&l----------------------------"
  listed:
    format: "&7%rank_prefix% &8- &b%rank_pending_time%&7/&b%rank_needed_time%"
    formatAlready: "&7%rank_prefix% &8- &b&b%rank_needed_time% &7(obtenido)"
    send:
      - "&7&m&l----------------------------"
      - "&7Rank list:"
      - "%ranks%"
      - "&7&m&l----------------------------"

ranked:
  all:
    - "&7&m&l----------------------------"
    - "&7ยก&b%player% &7rankup to &b%rank_prefix%&7!"
    - "&7&m&l----------------------------"
  own:
    - "&7&m&l----------------------------"
    - "&7ยก&7You rankup to &b%rank_prefix%&7!"
    - "&7&m&l----------------------------"