#################
# TimedRankups #
################

handle rankup commands:
  - "lp user %player% parent add %rank_name%"
  - "lp user %player% parent remove %old_rank_name%"

default rank: "default"

MySQL:
  Host: "127.0.0.1"
  Port: "3306"
  Username: "usrcx_locsql58"
  Password: "BhN7AsMqAeAUQkKaQ76GVkK43EJbxXuVsLcVEGQGN2pkeWq2eaQKwGqJb5cFBWdaaNs2GxZUe6v"
  Database: "survival"

enabled rankups: # Reverse order in order to have the priority to high ranks.
  - "red"
  - "green"
  - "aqua"
  - "purple"
  - "yellow"
  - "white"
  - "gold"
  - "cyan"
  - "pink"
  - "default"

rankups:
  default:
    time: 0 # seconds, put 0 for default.
    prefix: "&7✦"
  pink:
    time: 604800 # 1 week
    prefix: "&5✦"
  cyan:
    time: 2629800 # 1 month
    prefix: "&3✦"
  gold:
    time: 7889400 # 3 months
    prefix: "&6✦"
  white:
    time: 21038400 # 8 months
    prefix: "&f✦"
  yellow:
    time: 26298000 # 10 months
    prefix: "&e✦"
  purple:
    time: 31557600 # 1 year
    prefix: "&d✦"
  aqua:
    time: 39447000 # 1 year and 3 months
    prefix: "&b✦"
  green:
    time: 47336400 # 1 year and 6 months
    prefix: "&a✦"
  red:
    time: 63115200 # 2 years
    prefix: "&4✦"
