#################
# TimedRankups  #
#################

handle rankup commands:
  - "tellraw @a ["",{"text":"%player%","color":"aqua"},{"text":" just ranked up to","color":"white"},{"text":" %rank_prefix%","color":"green"},{"text":" more known as","color":"white"},{"text":" %rank_name%","color":"red"}]"
  - "lp user %player% parent add %rank_name%"
  - "lp user %player% parent remove %old_rank_name%"

default rank: "Usuario"

MySQL:
  Host: "localhost"
  Port: "3306"
  Username: "root"
  Password: "password"
  Database: "database"

enabled rankups: # Reverse order in order to have the priority to high ranks.
  - "Red"
  - "Green"
  - "Aqua"
  - "Purple"
  - "Yellow"
  - "White"
  - "Gold"
  - "Cyan"
  - "Pink"
  - "Usuario"

no more ranks: "&cUltimo Rango"

rankups:
  Usuario:
    time: 0 # seconds, put 0 for default.
    prefix: "&7Usuario"
  Pink:
    time: 604800 # 1 week
    prefix: "&5Pink"
  Cyan:
    time: 2629800 # 1 month
    prefix: "&3Cyan"
  Gold:
    time: 7889400 # 3 months
    prefix: "&6Gold"
  White:
    time: 21038400 # 8 months
    prefix: "&fWhite"
  Yellow:
    time: 26298000 # 10 months
    prefix: "&eYellow"
  Purple:
    time: 31557600 # 1 year
    prefix: "&dPurple"
  Aqua:
    time: 39447000 # 1 year and 3 months
    prefix: "&bAqua"
  Green:
    time: 47336400 # 1 year and 6 months
    prefix: "&aGreen"
  Red:
    time: 63115200 # 2 years
    prefix: "&4Red"

commands:
  see:
    next:
      - "&7&m&l----------------------------"
      - "&7Te falta &b%parsedTime% &7para"
      - "&7obtener el rango %new_rank_prefix%"
      - "&7&m&l----------------------------"
    noMore:
      - "&7&m&l----------------------------"
      - "&7You're in the last rankup."
      - "&7&m&l----------------------------"
  listed:
    format: "&7%rank_prefix% &8- &b%rank_pending_time%&7/&b%rank_needed_time%"
    formatAlready: "&7%rank_prefix% &8- &b&b%rank_needed_time% &7(obtenido)"
    send:
      - "&7&m&l----------------------------"
      - "&7Rank list:"
      - "%ranks%"
      - "&7&m&l----------------------------"

ranked:
  all:
    - "&7&m&l----------------------------"
    - "&7ยก&b%player% &7rankup to &b%rank_prefix%&7!"
    - "&7&m&l----------------------------"
  own:
    - "&7&m&l----------------------------"
    - "&7ยก&7You rankup to &b%rank_prefix%&7!"
    - "&7&m&l----------------------------"
