name: TimedAutoRankup
version: ${project.version}
main: online.nasgar.timedrankup.TimedRankup
api-version: 1.18
depend: [ Vault, PlaceholderAPI ]
authors: [ gatogamer, NasgarNetwork ]
description: A simple plugin to get timed rankups
website: https://insaneprojects.club

commands:
  rankup:
    - rango
    - rank
    - listrankups
  nextrankup:
    aliases:
      - nrankup
      - nrank
      - nextrank
      - siguienterankup
      - siguienterango
      - srankup
      - srank