main: online.nasgar.timedrankup.TimedRankup
name: TimedAutoRankup
version: ${project.version}
description: A simple plugin to get timed rankups

api-version: 1.18

depend: [ Vault, PlaceholderAPI ]

authors: [ gatogamer, NasgarNetwork ]


commands:
  rankup:
    - rango
    - rank
    - listrankups
  nextrankup:
    aliases:
      - nrankup
      - nrank
      - nextrank
      - siguienterankup
      - siguienterango
      - srankup
      - srank