name: TimedRankup
version: ${project.version}
main: me.gatogamer.timedrankup.TimedRankup
api-version: 1.17
depend: [ Vault, PlaceholderAPI ]
authors: [ gatogamer ]
description: A simple plugin to get timed rankups
website: https://insaneprojects.club

commands:
  seerankup:
  seenextrankup: