name: TimedRankup
version: ${project.version}
main: online.nasgar.timedrankup.TimedRankup
api-version: 1.17
depend: [ Vault, PlaceholderAPI ]
authors: [ gatogamer, NasgarNetwork ]
description: A simple plugin to get timed rankups
website: https://insaneprojects.club

api: "1.8"

command:
  seerankup: See your rankup
  seenextrankup: See your next rankup