name: TimedRankup
main: online.nasgar.timedrankup.TimedRankup
version: ${project.version}
description: A simple plugin to get timed rankups

depends: [ Vault, PlaceholderAPI ]
api-version: 1.13

authors: [ gatogamer, NasgarNetwork Development Team]

commands:
  rankup:
  nextrankup: