name: Release new version
on: [ 'push', 'pull_request' ]
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Check source
        uses: actions/checkout@v3

      - name: Build
        run: mvn clean package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          path: "**/target"

      #- name: Deploy with Maven
      #  run: mvn deploy -X
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: [ build ]
    runs-on: ubuntu-18.04

    steps:
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Set up Node.js v16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - uses: actions/checkout@v3

      - name: Grant execute permission for update-versions.sh
        run: chmod +x update-versions.sh

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_URL: "https://api.github.com/"
        run: npx --legacy-peer-deps -p @semantic-release/changelog -p @semantic-release/git -p @semantic-release/exec -p gradle-semantic-release-plugin -p semantic-release semantic-release