name: Deploy to Nasgar Repo
on: [ 'push', 'pull_request' ]
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Check source
        uses: actions/checkout@v3

      - name: Build
        run: mvn clean package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          path: "../../target/"

      #- name: Deploy with Maven
      #  run: mvn deploy -X
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}