name: Deploy to Nasgar Repo
on: [ 'push', 'pull_request' ]
jobs:
  build:
    runs-on: ubuntu-18.04
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Deploy with Maven
        run: mvn clean deploy